name: scalepopgen_0.1.1
channels:
        - conda-forge
        - bioconda
        - defaults
dependencies:
        - conda-forge::python=3.10
        - conda-forge::libglib=2.74.1
        - conda-forge::pyyaml=6.0
        - conda-forge::numpy=1.25.0
        - conda-forge::folium=0.14.0
        - conda-forge::geopy=2.3.0
        - conda-forge::libffi=3.4.2
        - conda-forge::libdeflate=1.13
        - conda-forge::r-rcolorbrewer=1.1_3
        - conda-forge::r-optparse=1.7.3
        - conda-forge::r-ggplot2=3.4.0
        - conda-forge::biopython=1.80
        - conda-forge::scipy=1.10.0
        - conda-forge::matplotlib=3.6.2
        - conda-forge::statsmodels=0.13.5
        - conda-forge::jinja2=3.1.2
        - conda-forge::r-base=4.2.2
        - conda-forge::r=4.2
        - conda-forge::r-optm=0.1.6
        - conda-forge::gawk=5.1.0
        - conda-forge::bokeh=3.2.1
        - conda-forge::toytree=2.0.5
        - conda-forge::ete3=3.1.3
        - bioconda::htslib=1.17
        - bioconda::pysam=0.20.0
        - bioconda::vcftools=0.1.16
        - bioconda::plink=1.90b6.21
        - bioconda::plink2=2.00a3.7
        - bioconda::eigensoft=8.0.0
        - bioconda::admixture=1.3.0
        - bioconda::treemix=1.13
        - bioconda::admixtools=7.0.2
        - bioconda::selscan=1.2.0a
        - bioconda::beagle=5.2_21Apr21.304
        - bioconda::bioconductor-snprelate=1.32.0
        - bioconda::fastindep=1.0.0
        - bioconda::phylip=3.697
        - bioconda::pybedtools=0.9.0
        - bioconda::sweepfinder2=1.0
        - bioconda::r-pophelper=2.3.1
        - bioconda::est-sfs=2.04-0
